name: 'GCR Deploy'
description: 'Deploy a Docker image to Google Container Registry (GCR)'
inputs:
  host:
    description: 'Hostname of the registry'
    required: true
    default: 'gcr.io'
  project:
    description: 'Name of the Google Cloud Platform project where your registry resides (example: foobar-191284)'
    required: true
  image:
    description: 'Name of the Docker image to push'
    required: true
  tag:
    description: 'Tag of the Docker image to push'
    required: true
  tag-as-latest:
    description: 'Whether or not to tag the pushed image with the "latest" tag'
    required: false
    default: 'false'
  digest-check:
    description: 'Whether or not to compare the digests of the locally built Docker image with the "latest" remote image.'
    required: false
    default: 'true'
  latest-tag:
    description: 'The name of the tag used to mark an image as "latest".'
    required: false
    default: 'latest'
runs:
  using: 'node12'
  main: 'dist/index.js'
